# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      #- --entrypoints.web.address=:80
      #- --entrypoints.websecure.address=:443
      #- --providers.docker
      # dashboard
      # for enabling /dashboard set api.insecure to true
      # after that create a ssh tunnel to 8080 an visit it @ localhost:8080
      # ssh docker@195.37.232.181 -L 8080:localhost:8080 
      #- --api.insecure=true
      # end dashboard
      #- --providers.docker.exposedbydefault=false
      #- --certificatesresolvers.leresolver.acme.email=me@example.com
      # make sure acme.json has chmod 600
      #- --certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json
      #- --certificatesresolvers.leresolver.acme.tlschallenge=true
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      #- "traefik.enable=true"

      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      #- "traefik.http.routers.http-catchall.entrypoints=web"
      #- "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      #- "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
  

  nginx:
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    links:
      - ckan
    #ports:
    #  - "0.0.0.0:80:80"
    depends_on: 
      - "ckan"
    networks:
      - proxy
      - http
    restart: on-failure
    labels:
      - "traefik.http.routers.nginx.rule=Host(`nginx.docker.localhost`)"
      #- "traefik.port=80"
      #- "traefik.enable=true"
      #- "traefik.http.routers.nginx.rule=Host(`ckan-dev.cuprit.net`)"
      #- "traefik.http.routers.nginx.entrypoints=websecure"
      #- "traefik.http.routers.nginx.tls=true"
      #- "traefik.http.routers.nginx.tls.certresolver=leresolver"
    
  ckan:
    container_name: ckan
    build:
      context: ckan/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    networks:
      - http
    depends_on:
      - "db"
      - "solr"
      - "redis"
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
    labels:
      - traefik.enable=false

  datapusher:
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"
    networks:
      - http
    labels:
      - traefik.enable=false

  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - http
    labels:
      - traefik.enable=false
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    build:
      context: solr/
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    labels:
      - traefik.enable=false
    networks:
      - http

  redis:
    container_name: redis
    image: redis:latest
    labels:
      - traefik.enable=false
    networks:
      - http

volumes:
  ckan_storage:
  pg_data:
  solr_data:

networks:
  proxy:
  http: