# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.

version: "3"

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    container_name: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --providers.docker.exposedbydefault=true
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - http
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    links:
      - ckan
    networks:
      - http
    depends_on:
      - "ckan"
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`ckan`)"
      - "traefik.http.routers.traefik.entrypoints=web"

  ckan:
    container_name: ckan
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    networks:
      - http
      - local
    depends_on:
      - "db"
      - "solr"
      - "redis"
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions

    labels:
      - traefik.enable=false

  datapusher:
    container_name: datapusher
    image: keitaro/ckan-datapusher:0.0.17
    networks:
      - local
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=false
    environment:
      - DATAPUSHER_VERSION=0.0.17
      - DATAPUSHER_MAX_CONTENT_LENGTH=10485760
      - DATAPUSHER_CHUNK_SIZE=16384
      - DATAPUSHER_CHUNK_INSERT_ROWS=250
      - DATAPUSHER_DOWNLOAD_TIMEOUT=30
      - DATAPUSHER_SSL_VERIFY=False
      - DATAPUSHER_REWRITE_RESOURCES=True
      - DATAPUSHER_REWRITE_URL=http://ckan:5000

  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - pg_data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    networks:
      - local
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    build:
      context: solr/
    networks:
      - local
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    labels:
      - traefik.enable=false

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - local
    labels:
      - traefik.enable=false

volumes:
  ckan_storage:
  pg_data:
  solr_data:

networks:
  local:
  http:
